global:
    smtp_from: 'example@gmail.com'
    smtp_smarthost: smtp.gmail.com:587
    smtp_auth_username: 'example@gmail.com'
    smtp_auth_identity: 'example@gmail.com'
    smtp_auth_password: 'exmplpsswd'

route:
  # fallback receiver
  receiver: admin
  group_wait: 40s
  group_interval: 5m
  repeat_interval: 30m
  routes:
    # Star Solutions.
  - match_re:
      app_type: (linux|windows)
    # fallback receiver 
    receiver: ss-admin
    routes:
    # Linux team
    - match:
        app_type: linux
      # fallback receiver
      receiver: linux-team-admin
      group_by: [category]
      routes:
      - match:
          severity: critical
        receiver: linux-team-manager
        continue: true
      - match:
          severity: warning
        receiver: linux-team-lead


    # Windows team
    - match:
        app_type: windows
      # fallback receiver
      receiver: windows-team-admin
      routes:
      - match:
          severity: critical
        receiver: windows-team-manager
      - match:
          severity: warning
        receiver: windows-team-lead

    # PEC Technologies.
  - match_re:
      app_type: (python|go)
    # fallback receiver 
    receiver: pec-admin
    routes:
    # Python team
    - match:
        app_type: python
      # fallback receiver
      receiver: python-team-admin
      routes:
      - match:
          severity: critical
        receiver: python-team-manager
      - match:
          severity: warning
        receiver: python-team-lead

    # Go team
    - match:
        app_type: go
      # fallback receiver
      receiver: go-team-admin
      routes:
      - match:
          severity: critical
        receiver: go-team-manager
      - match:
          severity: warning
        receiver: go-team-lead

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'


receivers:
- name: admin
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'admin is Down'
    text: "test notification"

- name: ss-admin
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'ss-admin is Down'
    text: "test notification"

- name: linux-team-admin
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'linux-team-admin is Down'
    text: "test notification"

- name: linux-team-lead
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'linux-team-lead is Down'
    text: "test notification"

- name: linux-team-manager
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'linux-team-manager is Down'
    text: "test notification"

- name: windows-team-admin
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'windows-team-admin is Down'
    text: "test notification"

- name: windows-team-lead
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'windows-team-lead is Down'
    text: "test notification"

- name: windows-team-manager
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'windows-team-manager is Down'
    text: "WMI"

- name: pec-admin
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'pec-admin is Down'
    text: "test notification"

- name: python-team-admin
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'python-team-admin is Down'
    text: "test notification"

- name: python-team-lead
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'expopython-team-lead   is Down'
    text: "test notification"

- name: python-team-manager
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'python-team-manager is Down'
    text: "test notification"

- name: go-team-admin
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'go-team-admin is Down'
    text: "test notification"

- name: go-team-lead
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'go-team-lead is Down'
    text: "test notification"

- name: go-team-manager
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'go-team-manager  is Down'
    text: "test notification"
